services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/fastapi_db?sslmode=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_SSL=false
      - SSL_MODE=disable
      - ENVIRONMENT=development
      - DEBUG=True
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - fastapi-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=fastapi_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - fastapi-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - fastapi-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - fastapi-network

volumes:
  postgres_data:
  redis_data:

networks:
  fastapi-network:
    driver: bridge